base_images:
  mapt:
    name: mapt
    namespace: ci
    tag: v0.7.0
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.20
  use_build_cache: true
images:
- context_dir: .ibm/images
  dockerfile_path: Dockerfile
  to: showcase-e2e-runner
- from: mapt
  to: mapt-runner
promotion:
  to:
  - name: rhdh
    namespace: ci
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.15"
resources:
  '*':
    limits:
      memory: 5Gi
    requests:
      cpu: 500m
      memory: 2Gi
tests:
- as: e2e-tests
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: rhdh
    product: ocp
    timeout: 1h0m0s
    version: "4.17"
  skip_if_only_changed: ^docs/|showcase-docs/|^\.changeset/|CONTRIBUTING\.md|OWNERS|README\.md|USAGE_DATA\.md|^scripts/|^\.github/|\.threatmodel/|^ui/|\.md$
  steps:
    test:
    - ref: janus-idp-backstage-showcase
    workflow: generic-claim
- as: e2e-tests-nightly
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: rhdh
    product: ocp
    timeout: 1h0m0s
    version: "4.17"
  cron: 0 7 * * *
  steps:
    test:
    - ref: janus-idp-backstage-showcase-nightly
    workflow: generic-claim
- as: e2e-tests-nightly-ocp-v4-16
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: rhdh
    product: ocp
    timeout: 1h0m0s
    version: "4.16"
  cron: 0 7 * * *
  steps:
    env:
      OC_CLIENT_VERSION: stable-4.16
    test:
    - ref: janus-idp-backstage-showcase-nightly
    workflow: generic-claim
- as: e2e-tests-nightly-ocp-v4-15
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: rhdh
    product: ocp
    timeout: 1h0m0s
    version: "4.15"
  cron: 0 7 * * *
  steps:
    env:
      OC_CLIENT_VERSION: stable-4.15
    test:
    - ref: janus-idp-backstage-showcase-nightly
    workflow: generic-claim
- as: e2e-tests-nightly-aks
  cron: 0 7 * * *
  steps:
    test:
    - as: janus-idp-backstage-showcase-helm-aks-mapt-create
      commands: |
        cd $SHARED_DIR
        azure aks create \
          --project-name "aks" \
          --backed-url "file:///workspace" \
          --conn-details-output "/workspace" \
          --spot \
          --enable-app-routing
      credentials:
      - mount_path: /tmp/secrets
        name: rhdh
        namespace: test-credentials
      from: mapt-runner
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
        requests:
          cpu: "2"
          memory: 6Gi
    - ref: janus-idp-backstage-showcase-helm-aks-nightly
    - as: janus-idp-backstage-showcase-helm-aks-mapt-destroy
      commands: "cd $SHARED_DIR\nazure aks destroy \\\n  --project-name \"aks\" \\\n
        \ --backed-url \"file:///workspace\" \n"
      credentials:
      - mount_path: /tmp/secrets
        name: rhdh
        namespace: test-credentials
      from: mapt-runner
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
        requests:
          cpu: "2"
          memory: 6Gi
- as: e2e-tests-nightly-gke
  cron: 0 7 * * *
  steps:
    test:
    - ref: janus-idp-backstage-showcase-helm-gke-nightly
zz_generated_metadata:
  branch: main
  org: janus-idp
  repo: backstage-showcase
